### ISSUE TITLE
Problem with missing author

### ISSUE THREAD

**Issue by ctron** [trustification/trustify-ui#114]
It looks like the UI has an issue when the author is missing: 

![image](https://github.com/user-attachments/assets/dffc55b5-0ac0-4dde-9c3c-ce97c965081e)

**Comment by ctron** [comment]
I guess it was this one: [bom.json](https://github.com/user-attachments/files/16283226/bom.json)

**Comment by carlosthe19916** [comment]
@ctron thanks for reporting this. The error is happening because the `author` field is NULL. The UI was expecting an empty array and not null.

I created this discussion https://github.com/trustification/trustify/discussions/568 to have an agreement between backend-clients in regards of how to treat Arrays.
