### ISSUE TITLE
Frontend goes crazy when backend reponds with 401

### ISSUE THREAD

**Issue by ctron** [trustification/trustify-ui#246]
When the backenend responds to requests with a `401`, the frontend seems to go crazy:

![image](https://github.com/user-attachments/assets/f91789af-89ac-469f-9649-4c9f2a980a7c)

Thousands of errors in seconds, leading to an unresponsive browser tab.

My expectation would be, that the user gets an error message.

**Comment by carlosthe19916** [comment]
@ctron can you provide a step by step way of reproducing the 401 error?

**Comment by ctron** [comment]
Send an invalid token instead of a valid one.

**Comment by carlosthe19916** [comment]
@ctron This issue has been raised indicating that there are 401 errors coming out of the backend.

I need to politely ask you to be more diligent on helping reproducing issues you reported. I can not verify whether or not a fix is correctly done unless I can reproduce the issue.

Can you please provide a step by step process on how to start the backend in order to get 401 errors and be able to reach to the point where your screenshot is describing?

**Comment by ctron** [comment]
Yes. Instead of sending a valid bearer token, send an invalid one. Maybe just do something like:

```
let token = get_token();
token = token + "something";
sendRequest(request, token);
```
