### ISSUE TITLE
UI doesn't respect ODIC issuer URL

### ISSUE THREAD

**Issue by ctron** [trustification/trustify-ui#34]
Despite having a configuration of `http://localhost:8090/realms/trustify`, the UI still tries to contact: `http://localhost:8180/trustify/.well-known/openid-configuration`

**Comment by carlosthe19916** [comment]
@ctron could you share some specific steps how to reproduce the issue? The source code does not have any mention to the port `8180` so I am curious where that thing comes from.

**Comment by carlosthe19916** [comment]
> Here's the (draft) PR: [trustification/trustify#332](https://github.com/trustification/trustify/pull/332)
> 
> You can enable that feature by running:
> 
> ```
> cargo run -p trustify-trustd --features garage-door -- api --devmode --embedded-oidc
> ```

- It seems your PR is using an embedded OIDC provider.
- I should test the UI OIDC thing against proven providers E.g. Keycloak or any other equivalent.
  - If it works with them, then the problem might be located in your embeeded oidc provider
  - If it doesn't work, then the problem is in the UI.

I have created a draft PR in the trustification repository https://github.com/trustification/trustify/pull/333 . This PR has detailed instructions on how to make the UI work with Keycloak. I didn't find any issues. So, it makes me think that there is no issues in the UI side but somewhere else.

Could you test my PR and see the UI working against Keycloak? If it works with Keycloak, I would say the root of the problem is your embedded oidc (and I can not test/guarantee how well or bad the embedded oidc provider works)

**Comment by ctron** [comment]
So just running this with your PR won't work, as it will result in a 401 when loading the UI. I wondering how you have tested it?

**Comment by carlosthe19916** [comment]
> So just running this with your PR won't work, as it will result in a 401 when loading the UI. I wondering how you have tested it?

@ctron 

I wonder the same, how you tested it? I am attaching a video where I run the commands detailed in my PR.

https://github.com/trustification/trustify-ui/assets/2582866/4abf4bf5-3ab8-43cd-bbb0-d97793a04f47

If we both have checkout exactly the same branch (my PR) I wonder why we, both, might have different results, we are missing something

**Comment by ctron** [comment]
https://github.com/trustification/trustify-ui/assets/202474/55da8d16-d4fa-4893-b6e0-ed625d8403ba

**Comment by carlosthe19916** [comment]
@ctron thanks for the video. I can see we both are not executing the same command.
- I executed `cargo run --bin trustd` as explained in my PR
- You are executing `cargo run --bin trustd -- api --devmode`

So that is why we have different results. And after watching your video I get some guesses:
- I could not see any login in your Video which indicates that not even the index.html page was possible to be loaded (due to 401 error)
- `The 401 Error` is being throw by the server (the UI does not play a role in that game). The server is blocking the static data (index.html) to be fetched by the browser. So the server must allow "public" access to the "index.html and static resources"; this is a configuration to be done in the server and not in the UI. Does it makes sense to you? what do you think?

**Comment by carlosthe19916** [comment]
> I know. But when you don't get a 401, then authentication is disabled. I am wondering how good that test is in this case.

You could try perhaps?

```shell
docker run --network="host" \
-e TRUSTIFICATION_API_URL=http://localhost:8080 \
-e AUTH_REQUIRED=true \
-e OIDC_SERVER_URL=http://localhost:8090/realms/chicken \
-e OIDC_CLIENT_ID=frontend \
-e OIDC_SCOPE=openid \
-e ANALYTICS_ENABLED=false \
-e PORT=3000 \
-p 3000:3000 \
ghcr.io/trustification/trustify-ui:latest
```

And then open http://localhost:3000


In general We can not test the UI that is served through the backend  because the backend code is not ready:

- The first step is to make changes into the main branch of the trustify repository to allow the static files to be exposed as "public" even when the backend has authentication enabled. This is change purely done in the backend
- Only after the previous requirement is done, we can test the UI but keeping in mind that we should test it with proven providers like Keycloak to correctly track where any issue might be (the UI or the oidc provider)

**Comment by ctron** [comment]
Here is where the 8180 is coming from: https://github.com/trustification/trustify/blob/main/server/src/lib.rs#L161

I noticed that when the UI goes into that infinity reload loop, it also doesn't seem to refresh from the server. So making a change on the server side should work, but doesn't. Closing the tab and reloading in a new tab makes it accept the changes.

Not sure who's to blame for this.

**Comment by carlosthe19916** [comment]
I suggest going slow step by step.

- I have checkout my PR https://github.com/trustification/trustify/pull/333
- Started Keycloak with `docker-compose -f etc/deploy/compose/compose.yaml up`
- Started Trustify with `env DB_USER=postgres DB_PASSWORD=eggs cargo run -p trustify-trustd -- api --devmode`
- Finally started the UI with:

```
docker run --network="host" \
-e TRUSTIFICATION_API_URL=http://localhost:8080 \
-e AUTH_REQUIRED=true \
-e OIDC_SERVER_URL=http://localhost:8090/realms/chicken \
-e OIDC_CLIENT_ID=frontend \
-e OIDC_SCOPE=openid \
-e ANALYTICS_ENABLED=false \
-e PORT=3000 \
-p 3000:3000 \
ghcr.io/trustification/trustify-ui:latest
```

Open http://localhost:3000 and everything works. That to me indicates the UI works fine with Keycloak and when the static data can be fetched by the browser. Could you try the steps described above?

If you can confirm my commands above work for you, then the tasks can be done in 2 steps:
- Allow the backend to expose the static files as public regardless of whether or not auth has been enabled in trustify
- Test the Trustify repo can work against Keycloak. Fix any issue wherever it appears
- Only then introduce a customized embedded oidc provider

**Comment by ctron** [comment]
I think we are good here. Closing the tab and starting fresh in a new one makes the UI update the issuer URL.
