### ISSUE TITLE
The upload pane is confusing

### ISSUE THREAD

**Issue by ctron** [trustification/trustify-ui#59]
Steps:

* Click the upload button
* Click the upload button on the pane
* Select an SBOM that fails
* Click the upload button on the pane again
* Select an SBOM that succeeds

The result looks like this:

![image](https://github.com/trustification/trustify-ui/assets/202474/98369167-6da2-4544-87dc-0b6043604918)

Its color says "ok", it still says "0 of 1" files uploaded, the SBOM was in fact not uploaded.

**Comment by carlosthe19916** [comment]
Waiting on https://github.com/trustification/trustify/issues/294 to be solved in order to make changes to the UI. The current Upload SBOM does not work and I agree needs to be evaluated

**Comment by carlosthe19916** [comment]
Looks like this is the same bug reported at https://github.com/trustification/trustify-ui/issues/265 which was recently fixed.

**Comment by carlosthe19916** [comment]
As https://github.com/trustification/trustify-ui/issues/265 was fixed by https://github.com/trustification/trustify-ui/pull/267 and the problem described in this issue is the same I will close this issue.

If the issue described here was different from https://github.com/trustification/trustify-ui/issues/265 therefore not fixed yet, we can reopen this issue.
